version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-development}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      APP_VERSION: ${APP_VERSION:-0.1.0}
      POSTGRES_URL: ${POSTGRES_URL:-postgresql+psycopg://postgres:postgres@postgres:5432/postgres}
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:postgres@postgres:5432/postgres}
      DB_POOL_SIZE: ${DB_POOL_SIZE:-10}
      QDRANT_URL: ${QDRANT_URL:-http://qdrant:6333}
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - qdrant

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"

volumes:
  postgres_data:
