name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      LOG_LEVEL: INFO
      APP_VERSION: 0.1.0
      POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/postgres
      QDRANT_URL: http://localhost:6333
      QDRANT_API_KEY: ""
      EMBEDDING_MODEL: nomic-embed-text
      EMBEDDING_FALLBACK_MODELS: ""
      OLLAMA_BASE_URL: http://localhost:11434
      VECTOR_DIM: 1536
      VECTOR_TIMEOUT_SECONDS: 10.0
      LOCAL_INGEST_ROOT: ./tests/fixtures/docs
      CHUNK_SIZE: 200
      CHUNK_OVERLAP: 20
      INGEST_DEFAULT_TENANT: default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libmagic1

      - name: Install dependencies
        run: pip install .[dev]

      - name: Lint
        run: ruff check backend

      - name: Test
        run: pytest backend/tests tests/ingestion
